services:
  - type: web
    name: table-tenis-areana-2026
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: SAMPLE_FRAMES_DIR
        value: data/sample_frames
      - key: UPLOAD_DIR
        value: uploads
